Catch RateLimitExceeded and log a message instead
transferwise/pipelinewise-tap-github pull request #5
Opened 2021-07-09 21:56 UTC by rafael-lima-tw

## Problem

We don't need to throw a API Rate limit exception on do_sync anymore, instead, we want to log it

## Proposed changes

* Don't throw Rate Limit exception on do_sync, only on do_discover
* Refactor do_sync to call a sync_repositories instead
* Add test for do_sync and its refactor
* Add test for do_discover

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

2021-07-13 13:38 UTC, diegofurtados approved these changes

2021-07-13 15:50 UTC, koszti commented on tap_github/__init__.py
> +        logger.warning(f"API rate limit has been reached:{e}")
This will log as warning and exit as success without loading any new data. Is this really what we want?

Why not waiting until `X-RateLimit-Reset: <epoc-timestamp>` returned by github API as detailed in https://transferwise.atlassian.net/browse/AP-974?

2021-07-14 02:55 UTC, rafael-lima-tw commented on tap_github/__init__.py
> +        logger.warning(f"API rate limit has been reached:{e}")
Regarding the catching of RateLimitExceeded - After a grooming with @louis-pie and @Samira-El we decided that we should not raise RateLimitExceeded in the do_sync as this could generate a lot of noise for the team. Instead, we would exit gracefully and log instead. Of course this means that we need to monitor the logs to see if we are able to gather the data we need.

We initially thought of changing the hard coded 600s sleep in the RateTrotlling function to be configurable in order to wait a little longer as we felt that 10 min could be too short and we could use up to 1 hour. However, after some discussion, we thought that relying in the write_bookmark/write_state would be enough and thus, there wouldn't be any need for sleeping.

2021-07-14 08:41 UTC, koszti requested changes

2021-07-14 08:41 UTC, koszti commented on tap_github/__init__.py
> +        logger.warning(f"API rate limit has been reached:{e}")
If we implement in this way then we'll miss data:

If the rate limit exceeds when not every page processed, then we will update the bookmark too early without processing all pages. The next run we will skip the unprocessed pages and we'll miss data without being notified. 

Furthermore returning success state if the code fails sounds logically incorrect.

2021-07-14 08:45 UTC, koszti commented on tap_github/__init__.py
> +        logger.warning(f"API rate limit has been reached:{e}")
> We initially thought of changing the hard coded 600s sleep

The github API returns the exact epoch timestamp and the remaining seconds we need to wait until the api limit reset. We don't need to to wait hard coded seconds, neither it needs to be configurable.

The github api gives when rate limit exceeded:
```
X-RateLimit-Remaining: 1234
X-RateLimit-Reset: 1615467631
```

2021-07-14 10:27 UTC, closed without merging